### ISSUE TITLE
Backend - refaktoring

### ISSUE THREAD

**Issue by tauchmanovaM** [SemStew/CMS#14]
# Refaktoring
## Opravit
_Výtažek z poznámek_
**Opravit v kódu:**
- Logo!
- překlepy "Represantation", "Controler", ...
- pojmenování package (com.vaadin.starter.SemStew) - řešili jsme
- package Services by bylo asi dobrý rozdělit ještě na dílčí funkční celky - takhle je to nepřehledné (Menu, RestaurantInfo, Reservation, ...)
- UI - vážně je všude copypasted stejné menu, footer, ... ??? proč, když jsou to třídy, tak můžou z něčeho dědit a přepsat jenom v případě potřeby... přidání nové položky do levého menu = upravit asi 10 souborů?! - Nutno opravit!
- žádná dokumentace kódu - dopsat komentáře!
- reviews-list.html je tam asi navíc... Smazat!

**Opravit naplněnost UC:**
 _- UC1:_ přihlašování k /admin není vyžadováno, register nic, login jen UI
 _- UC18:_ no ok, je tam tabulka - jedno menu, bez členění podle kategorií, bez filtru/řazení
 _- UC14-15:_ funguje CRUD, ale vyplňovat ID není moc hezké, pokud je restaurant jenom jeden a není možnost to měnit, tak to asi uživatel nemusí ani vědět
 _- UC19:_ informace se nepropaguje do veřejné části (About us/Contacts)
 _- UC3-UC5:_
  - přidání jídla: Internal server error (java.lang.NumberFormatException: For input string: "")
  - úprava, smazání: nejde zadat ID, pro úpravu není po výběru formulář předvyplněný

**Comment by vlktoma5** [comment]
### Issue 14
Opraveno, dodelano a mergenuto do mastera.
